### ISSUE TITLE
partial rar file is uncompressed failure

### ISSUE THREAD

**Issue by LightSmileMu** [adamhathcock/sharpcompress#379]
Exception is Invalid Rar Header: 216

at SharpCompress.Common.Rar.Headers.RarHeaderFactory.ReadNextHeader(Stream stream)
at SharpCompress.Common.Rar.Headers.RarHeaderFactory.<ReadHeaders>d__0.MoveNext()
at SharpCompress.Common.Rar.RarVolume.<GetVolumeFileParts>d__0.MoveNext()
at SharpCompress.Reader.Rar.RarReader.<GetEntries>d__0.MoveNext()
at SharpCompress.Reader.AbstractReader`2.LoadStreamForReading(Stream stream)
at SharpCompress.Reader.AbstractReader`2.MoveToNextEntry()
at SharpCompress.Reader.IReaderExtensions.WriteAllToDirectory(IReader reader, String destinationDirectory, ExtractOptions options)

**Comment by Nanook** [comment]
Possibly the same issue as #890 . Either way, I'm closing this as no further information was provided.
