### ISSUE TITLE
Use winrar to encrypt files, and file name encryption, throw an error when using SharpCompress to decompress

### ISSUE THREAD

**Issue by toolgood** [adamhathcock/sharpcompress#533]
Use winrar to encrypt files, and file name encryption, throw an error when using SharpCompress to decompress

.net core 3.1
SharpCompress  Version=0.26.0
 
throw error:  SharpCompress Arithmetic operation resulted in an overflow.

   at SharpCompress.IO.MarkingBinaryReader.ReadRarVIntByte(Int32 maxBytes)
   at SharpCompress.Common.Rar.Headers.RarHeader..ctor(RarCrcBinaryReader reader, Boolean isRar5, ArchiveEncoding archiveEncoding)
   at SharpCompress.Common.Rar.Headers.RarHeader.TryReadBase(RarCrcBinaryReader reader, Boolean isRar5, ArchiveEncoding archiveEncoding)
   at SharpCompress.Common.Rar.Headers.RarHeaderFactory.TryReadNextHeader(Stream stream)
   at SharpCompress.Common.Rar.Headers.RarHeaderFactory.<ReadHeaders>d__12.MoveNext()
   at SharpCompress.Common.Rar.RarVolume.<GetVolumeFileParts>d__10.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at SharpCompress.Archives.Rar.FileInfoRarArchiveVolume..ctor(FileInfo fileInfo, ReaderOptions options)
   at SharpCompress.Archives.Rar.RarArchiveVolumeFactory.<GetParts>d__1.MoveNext()
   at SharpCompress.LazyReadOnlyCollection`1.LazyLoader.MoveNext()
   at SharpCompress.Archives.Rar.RarArchiveEntryFactory.<GetFileParts>d__0.MoveNext()
   at SharpCompress.Archives.Rar.RarArchiveEntryFactory.<GetMatchedFileParts>d__1.MoveNext()
   at SharpCompress.Archives.Rar.RarArchiveEntryFactory.<GetEntries>d__2.MoveNext()
   at SharpCompress.LazyReadOnlyCollection`1.LazyLoader.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at SharpCompress.Archives.IArchiveExtensions.WriteToDirectory(IArchive archive, String destinationDirectory, ExtractionOptions options)

**Comment by adamhathcock** [comment]
Rar5 decryption isn't implemented
