### ISSUE TITLE
System.NotSupportedException on reader.MoveToNextEntry()

### ISSUE THREAD

**Issue by Stuart88** [adamhathcock/sharpcompress#605]
Unzipping a 7z file fails with `System.NotSupportedException` on the last `MoveToNextEntry()` call.

On inspecting the results in file explorer, I can see it's successfully finished extraction, so the issue seems to be that `MoveToNextEntry()` just doesn't realise it's reached the end of the archive.

If it helps, the 7z archive I'm working with can be downloaded here: https://www.nexusmods.com/oblivion/mods/5296?tab=files&file_id=1000024710

Stack Trace:

```
   at SharpCompress.Compressors.LZMA.DecoderRegistry.CreateDecoderStream(CMethodId id, Stream[] inStreams, Byte[] info, IPasswordProvider pass, Int64 limit)
   at SharpCompress.Compressors.LZMA.DecoderStreamHelper.CreateDecoderStream(Stream inStream, Int64 startPos, Int64[] packSizes, CFolder folderInfo, IPasswordProvider pass)
   at SharpCompress.Common.SevenZip.ArchiveDatabase.GetFolderStream(Stream stream, CFolder folder, IPasswordProvider pw)
   at SharpCompress.Archives.SevenZip.SevenZipArchive.SevenZipReader.<GetEntries>d__7.MoveNext()
   at SharpCompress.Readers.AbstractReader`2.MoveToNextEntry()
   at U_Mod.Models.ZipFileWorker.UncompressZip(String inFile, String outDirectory) in C:\Users\saitk\Programming\WPF\U-Mod\U-Mod\Models\ZipFileWorker.cs:line 181
```

**Comment by DMW007** [comment]
If you're extracting using the [`ReaderFactory`](https://github.com/adamhathcock/sharpcompress/blob/master/src/SharpCompress/Readers/ReaderFactory.cs), it seems that 7z support is missing there. As an workaround, you can try open it manually with `SevenZipArchive.Open()`. But the progress seems not to work using this way and self-writing a wrapper doesn't work because the `RewindableStream` class is mostly declared as internal.

**Comment by adamhathcock** [comment]
Thanks for helping @DMW007 

Readers aren't used with 7Zip because 7Zip requires random access on the stream.  Reader is built for non-seekable streams while Archive is built for seekable streams.

**Comment by DMW007** [comment]
Thank you @adamhathcock for the explanation. I'd suggest to document this in the usage guide, so it's clear that the auto extractor cannot work with 7zip archives.

**Comment by adamhathcock** [comment]
ArchiveFactory does work with 7Zip though
