### ISSUE TITLE
rar header crc mismatch

### ISSUE THREAD

**Issue by ghostriderinthesky** [adamhathcock/sharpcompress#676]
Hi

When trying to open some RAR files, I get this exception below. What does it mean and how to solve it?

SharpCompress.Common.InvalidFormatException
  HResult=0x80131500
  Message=rar header crc mismatch
  Source=SharpCompress
  StackTrace:
   at SharpCompress.Common.Rar.Headers.RarHeader.VerifyHeaderCrc(UInt32 crc32)
   at SharpCompress.Common.Rar.Headers.RarHeader..ctor(RarHeader header, RarCrcBinaryReader reader, HeaderType headerType)
   at SharpCompress.Common.Rar.Headers.RarHeaderFactory.TryReadNextHeader(Stream stream)
   at SharpCompress.Common.Rar.Headers.RarHeaderFactory.<ReadHeaders>d__12.MoveNext()
   at SharpCompress.Common.Rar.RarVolume.<GetVolumeFileParts>d__10.MoveNext()
   at SharpCompress.Archives.Rar.RarArchiveEntryFactory.<GetFileParts>d__0.MoveNext()
   at SharpCompress.Archives.Rar.RarArchiveEntryFactory.<GetMatchedFileParts>d__1.MoveNext()
   at SharpCompress.Archives.Rar.RarArchiveEntryFactory.<GetEntries>d__2.MoveNext()
   at SharpCompress.LazyReadOnlyCollection`1.LazyLoader.MoveNext()

**Comment by adamhathcock** [comment]
Likely corrupt archives.  Check with WinRAR or similar

**Comment by ghostriderinthesky** [comment]
Thx. Problem solved!
