### ISSUE TITLE
.tar.7z support

### ISSUE THREAD

**Issue by SupinePandora43** [adamhathcock/sharpcompress#751]
stacktrace:
```
SharpCompress.Compressors.LZMA.DataErrorException: Data Error
   at SharpCompress.Compressors.LZMA.LzmaStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at SharpCompress.Compressors.LZMA.Utilites.Utils.ReadExact(Stream stream, Byte[] buffer, Int32 offset, Int32 length)
   at SharpCompress.Common.SevenZip.ArchiveReader.ReadAndDecodePackedStreams(Int64 baseOffset, IPasswordProvider pass)
   at SharpCompress.Common.SevenZip.ArchiveReader.ReadDatabase(IPasswordProvider pass)
   at SharpCompress.Archives.SevenZip.SevenZipArchive.LoadFactory(Stream stream)
   at SharpCompress.Archives.SevenZip.SevenZipArchive.LoadEntries(IEnumerable`1 volumes)
   at SharpCompress.Archives.AbstractArchive`2..ctor(ArchiveType type, SourceStream srcStream)
   at SharpCompress.Archives.SevenZip.SevenZipArchive..ctor(SourceStream srcStream)
   at SharpCompress.Archives.SevenZip.SevenZipArchive.Open(FileInfo fileInfo, ReaderOptions readerOptions)
   at SharpCompress.Archives.SevenZip.SevenZipArchive.Open(String filePath, ReaderOptions readerOptions)
```
file in question: [ultralightcore-bin-41a04e01-linux-x64.7z](https://ultralightcore-bin.sfo2.cdn.digitaloceanspaces.com/ultralightcore-bin-41a04e01-linux-x64.7z)
file sha256: `c6dd7e4ba5867fe763109263a5af8da40cf3e5cf46b91e4892eac76a49ec0746`

code to replicate:
```cs
SevenZipArchive.Open(file);
```

~~for some reason, i can't open it in `Ark`, but can in `Dolphin` 😕~~
Turns out it's `.tar.7z` archive!

**Comment by adamhathcock** [comment]
should easy to add to detection alongside gzip and bzip2

**Comment by btomblinson** [comment]
@adamhathcock any progress on this?

**Comment by btomblinson** [comment]
@adamhathcock this can be closed or do we want to add more features before we say we fully support it?

**Comment by btomblinson** [comment]
Pull request #763 closes this
