### ISSUE TITLE
NullReference Exception in RarRijndael.Initialize()

### ISSUE THREAD

**Issue by SirSparkles** [adamhathcock/sharpcompress#757]
Some Clients are reporting:

System.NullReferenceException: Object reference not set to an instance of an object.
     at SharpCompress.Common.Rar.RarRijndael.Initialize()
     at SharpCompress.Common.Rar.RarCryptoWrapper..ctor(Stream actualStream, String password, Byte[] salt)
     at SharpCompress.Archives.Rar.SeekableFilePart.GetCompressedStream()
     at SharpCompress.Compressors.Rar.MultiVolumeReadOnlyStream.InitializeNextFilePart()
     at SharpCompress.Archives.Rar.RarArchiveEntry.OpenEntryStream()
     at SharpCompress.Archives.IArchiveEntryExtensions.WriteTo(IArchiveEntry archiveEntry, Stream streamToWriteTo)
     at SharpCompress.Archives.IArchiveEntryExtensions.<>c__DisplayClass2_0.<WriteToFile>b__0(String x, FileMode fm)
     at SharpCompress.Common.ExtractionMethods.WriteEntryToFile(IEntry entry, String destinationFileName, ExtractionOptions options, Action`2 openAndWrite)

**Comment by labworkx** [comment]
Probably the same as https://github.com/adamhathcock/sharpcompress/issues/743

I encountered this error and was expecting a SharpCompress.Common.CryptographicException but got also a null reference.

**Comment by Erior** [comment]
Guess it is a bit inconvenient but please build sharpcompress from master branch and test with that, I don't think we have released the change that got merged for this issue.
